swagger: '2.0'
info:
  version: v1
  title: myapi
  description: my first api
  x-ibm-name: app
host: $(catalog.host)
basePath: /myapi
schemes:
  - https
produces:
  - application/json
paths:
  /Customers/v1:
    get:
      tags:
        - Customer
      description: Gets all Customers from the system that the user has access to
      operationId: getCustomer
      produces:
        - application/json
      x-swagger-router-controller: Customer
      responses:
        '200':
          description: Customer response
          schema:
            type: array
            items:
              $ref: '#/definitions/Customersv1'
        '404':
          description: Customer response
          schema:
            type: object
        '500':
          description: Customer response
          schema:
            type: object
      parameters:
        - name: pageSize
          in: query
          description: Number of records returned
          type: integer
        - name: pageNumber
          in: query
          description: Page number
          type: integer
    post:
      tags:
        - Customer
      description: Posts all Customers from the system that the user has access to
      operationId: postCustomer
      produces:
        - application/json
      consumes:
        - application/json
      x-swagger-router-controller: Customer
      responses:
        '204':
          description: Customer response
          schema:
            type: array
            items:
              $ref: '#/definitions/Customersv1'
        '404':
          description: Customer response
          schema:
            type: object
        '500':
          description: Customer response
          schema:
            type: object
      parameters:
        - name: Customers/v1
          in: body
          schema:
            $ref: '#/definitions/Customersv1'
definitions:
  ApiError:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Customersv1:
    type: object
    properties:
      type: {}
      properties:
        type: {}
      required: {}
    required:
      - type
      - properties
      - required
responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/ApiError'
  PersonDoesNotExistResponse:
    description: Person does not exist.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:8080'
  assembly:
    execute:
      - invoke:
          target-url: 'https://app.mybluemix.net$(request.path)$(request.search)'
          tls-profile: ''
          secure-gateway: false
    catch: []
